### ISSUE TITLE
Crash when copying text from first time receive window is shown

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#83]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

Crash when I, the receiver on CentOS 7, copied text. Worked up until some point.

Sender (Ubuntu 22.04):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xfc8070]

goroutine 285 [running]:
github.com/Jacalz/rymdport/v3/internal/util.(*ProgressBar).WithProgress.func1.1()
      github.com/Jacalz/rymdport/v3/internal/util/progress.go:19 +0x10
sync.(*Once).doSlow(0xc0036738c0?, 0xc006e9fd68?)
      sync/once.go:74 +0xc2
sync.(*Once).Do(...)
      sync/once.go:65
github.com/Jacalz/rymdport/v3/internal/util.(*ProgressBar).WithProgress.func1(0x3780?, 0x4d73e0?)
      github.com/Jacalz/rymdport/v3/internal/util/progress.go:19 +0x65
github.com/psanford/wormhole-william/wormhole.(*Client).SendText.func1()
      github.com/psanford/wormhole-william@v1.0.6/wormhole/send.go:170 +0x779
created by github.com/psanford/wormhole-william/wormhole.(*Client).SendText
      github.com/psanford/wormhole-william@v1.0.6/wormhole/send.go:71 +0x551
```

Receiver (CentOS 7):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfca704]

goroutine 54 [running]:
github.com/Jacalz/rymdport/v3/internal/transport.(*Client).showTextReceiveWindow.func2()
      github.com/Jacalz/rymdport/v3/internal/transport/display.go:51 +0x24
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc00406e000, 0xc002a22f01)
      fyne.io/fyne/v2@v2.3.4/widget/button.go:202 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
      fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
      fyne.io/fyne/v2@v2.3.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
      fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:946 +0x136
```

### Steps to Reproduce

1. Press the copy button on CentOS 7.

### Rymdport version

3.3.5

### Operating System

Linux

### Operating System Version

CentOS 7 and Ubuntu 22.04

### Go Compiler Version

1.19.6

**Comment by Jacalz** [comment]
The second crash seems to be unrelated to the first but is also already fixed on the `next` branch ready for v3.4.0 in a few weeks. Will close this as resolved.
